<?php
/**
* Implements hook_menu().
*/
function iowacourier_menu() {
  $items['iowacourier'] = array(
    'title' => 'IA Shares Delivery Schedule',
    'page callback' => 'mobius_iowacourier_display',
    'access arguments' => array('access content'),
  );
  return $items;
}

function mobius_iowacourier_getColumns()
{
    $ret = array();
    $query = 'SELECT * FROM iowa_courier_staging where id = -1';
    $result = db_query($query);
    $rows = $result->fetchAllAssoc('id');
    foreach(json_decode(json_encode($rows), True) as $r)
    {
        foreach ($r as $key => $value)
        {
            $ret[$key] = $value ? $value : $key;
        }
    }
    return $ret;
}

function mobius_iowacourier_generateHTMLTable()
{
    $colMap = mobius_iowacourier_getColumns();
    $ret = "<table id='iowa_courier_display_table'><thead><tr>";
    $colOrder = "";
    
    # Hard coded display columns. The rest are javascript displayed
    $displayOrder = array("library_name","county","city","hub","hub_city","day","route","stat_courier_pick_up_schedule","delivery_code");
    
    $militaryColumns = array(
        "stat_courier_pick_up_schedule",
        "monday_hours",
        "tuesday_hours",
        "wednesday_hours",
        "thursday_hours",
        "friday_hours",
        "saturday_hours",
        "sunday_hours"        
    );
    
    $javascriptColumns = array(
        "library_name" => "IOWACourierLibraryClick",
        "route" => "IOWACourierRouteClick"
    );
    
    $javascriptRemoveColumns = array(
        "contact_card",
        "id",
        "hours",
        "num",
        "nid",
        "changed",
        "size_code",
        "knackid",
    );
    
    $javascriptUIDetails = array(
        "groups" =>
            array(
            "Library Info" => array("mailing_address","physical_location_street_address","library_telephone_number","library_email_address","fax_number","web_address_url","monday_hours","tuesday_hours","wednesday_hours","thursday_hours","friday_hours","saturday_hours","sunday_hours"),
            "Courier Info" => array("silo_code","delivery_code","physical_address","hub","route","hub_city","day","stat_courier_pick_up_schedule","number_of_bags"),
            "Contacts" => array("directoradministrator","director_email_address","assistant_director","assistant_director_email_address","ill_contact","ill_email_address","ill_phone_number","ill_fax_number","childrens_services_librarian","childrens_services_email_address","teen_services_librarian","teen_services_librarian_email"),
            ),
        "group_order" => array("Library Info","Courier Info","Contacts"),
        "title_field" => "library_name"
    );
    
    foreach($displayOrder as $col)
    {
        $ret .= "<th>".$colMap[$col]."</th>";
        $colOrder.= $col.",";
    }
    foreach($colMap as $key => $value)
    {
        if(!in_array($key,$displayOrder))
        {
            $colOrder.= $key.",";
        }
    }
    $colOrder = substr($colOrder,0,-1);
    
    $ret .= "</tr></thead><tbody>";
    $metadata = array();
    $query = "SELECT $colOrder FROM iowa_courier_staging where id > -1 and library_name is not null and route is not null";
    $result = db_query($query);
    $rows = $result->fetchAllAssoc('id');
    foreach(json_decode(json_encode($rows), True) as $libraryRow)
    {
        $ret .= "<tr>";
        
        $metadata[$libraryRow["id"]] = array();
        foreach ($libraryRow as $key => $value)
        {
            $finalValue = in_array($key,$militaryColumns) ? mobius_iowacourier_figureMilitary($value) : $value;
            if(in_array($key,$displayOrder))
            {
                $ret .="<td libid='".$libraryRow["id"]."'>";
                $ending = "";
                if( isset($javascriptColumns[$key]) )
                {
                    $ret.="<a class='".$javascriptColumns[$key]."' onclick ='".$javascriptColumns[$key]."(this)' href='#' >";
                    $ending = "</a>";
                }
                $ret .="$finalValue$ending</td>";
            }
            $metadata[$libraryRow["id"]][$key] = $finalValue;
        }
        $ret .= "</tr>";
    }
    $ret .= "</tbody></table>
    <div style='display: none'>";
    foreach($metadata as $key => $value)
    {
        $ret.="<div class = 'library-hidden-data' id='iowacourier-metadata-$key'>\n";
        foreach($value as $int => $intval)
        {
            if(!(in_array($int,$javascriptRemoveColumns)))
            {
                $ret.="<span metaname = '$int' title ='".mobius_iowacourier_escape($colMap[$int])."'>$intval</span>\n";        
            }
        }
        $ret.="</div>\n";
    }
    $ret.="</div><script type='text/javascript'>
<!--//--><![CDATA[//><!--
    var displayGrouping = JSON.parse('{ ";
    foreach($javascriptUIDetails["groups"] as $groupName => $list)
    {
        $ret.="\"$groupName\" : [";
        foreach($list as $item)
        {
            $ret.="\"$item\",";
        }
        $ret = substr($ret,0,-1);
        $ret .= "],";
    }
    $ret = substr($ret,0,-1);
    $ret.="}');
    var displayGroupingOrder = JSON.parse('[ ";
    foreach($javascriptUIDetails["group_order"] as $groupName)
    {
        $ret.="\"$groupName\",";
    }
    $ret = substr($ret,0,-1);
    $ret.="]');
    var displayTitleField = '".$javascriptUIDetails["title_field"]."';
    //--><!]]>
    </script>";
    return $ret;
}

function mobius_iowacourier_escape($val)
{
    return str_replace("'", "", $val);
}

function mobius_iowacourier_figureMilitary($val)
{
    $val = trim($val);
    if(strlen($val) < 3)
    {
        return $val;
    }
    
    $each = array($val);
    if( (strpos($val, ' ') !== false)) // There could be a time "range" expressed with a space
    {
        $each[0] = explode(' ',$val);
    }
    $ret = "";
    foreach($each as $inter => $frag)
    {
        if(is_array($frag))
        {
            foreach($frag as $int => $low)
            {
                if(strpos($low, '-') !== false)
                {
                    $pair = explode('-',$low);
                    $ret .=  mobius_iowacourier_convertFromMilitary($pair[0]);
                    $ret .= "-" . mobius_iowacourier_convertFromMilitary($pair[1]);
                }
                else
                {
                    $ret .=  mobius_iowacourier_convertFromMilitary($low);
                }
                $ret .=  " , ";
            }
            $ret = substr($ret,0,-3);
        }
        else
        {
            $pair = explode('-',$frag);
            foreach($pair as $key => $value)
            {
                $ret .= "-" .  mobius_iowacourier_convertFromMilitary($value);
            }
            $ret = substr($ret,1);
        }
    }
    
    
    return $ret;
}

function mobius_iowacourier_convertFromMilitary($val)
{
    $val = trim($val);
    // Strip non numerics
    $val = preg_replace ('/[^\d]/','',$val);
    $am = "am";
    if($val >= 1200)
    {
        $am = "pm";
    }
    if($val >= 1300)
    {
        $val -= 1200;
    }
    
    $minute = substr($val,-2,2);
    $hour = preg_replace ('/(\d+?)\d\d$/','$1',$val);
    if(substr($hour,0,1) == "0")
    {
        $hour = substr($hour,1);
    }

    return $hour.':'.$minute.$am;
}



function mobius_iowacourier_display() {
  drupal_page_is_cacheable($allow_caching = FALSE);
  drupal_add_js('https://maps.googleapis.com/maps/api/js?key=AIzaSyAmPDE5_oFVJ22qY5IkoAJ_eQ-XJNKOlwM&callback=myMap', 'external');
  drupal_add_js('/sites/all/modules/iowacourier/iowacourier.js', 'external');

  $varColDump =  mobius_iowacourier_generateHTMLTable();
  $page = array (
    '#markup' =>
    '
    <style>
        .card-pane {
            border: 3px solid grey;
            position: absolute;
            width: 90%;
            padding: 2%;
            left: 5%;
            right: 5%;
            z-index: 1000;
            top: 16%;
            background-color: white;
        }
        .card-wrapper {
            background-color: white;
            margin: 12px;
        }
        .card-pane-inner {
            display: flex;
            flex-wrap: wrap;
        }
        .card-wrapper-label {
            font-color: black;
            font-weight: bold;
            font-size: 14pt;
        }
        .card-wrapper-data {
        }
        .card-pane-close {
            position: absolute;
            right: 0;
            top: 0;
        }
        .group-card-wrapper {
            min-width: 25%;
        }
        .group-card-wrapper-title {
            font-size: 18pt;
            text-align: center;
            border-bottom: 1px solid blue;
            width: 90%;
        }
        .card-title {
            font-size: 40pt;
            text-align: center;
            font-weight: bold;
            border-bottom: 1px solid black;
        }
        .iowacourier-map-display-map {
            min-width: 54%;
        }
        .iowacourier-map-display-table {
            width: 42%;
            padding: 21px 10px 0px 10px;
        }
        .iowacourier-waypoint-library-cell {
        }
        .iowacourier-waypoint-library-cell-name {
            font-weight: bold;
            font-size: 120%;
        }
        .iowacourier-waypoint-library-cell-address {
        }
        .iowacourier-waypoint-stop-cell {
            text-align: center;
            color: #EA4335;
            font-weight: bold;
            font-size: 20pt;
        }
        .iowacourier-waypoint-time-cell-data {
        }
        .iowacourier-map-lib-table th {
            text-align: center;
            width: auto;
        }
        .iowacourier-map-lib-table {
                width: auto;
            }
        
        @media only screen and (max-width: 1250px) {
            
        }

    </style>
    <h3>Important note:</h3>
<p>
Libraries can update individual library information in the State Library of Iowa\'s <a href="https://www.statelibraryofiowa.org/ld/c-d/directories/index">Iowa Library Directory</a>, and the information will appear on this page. </br>
Pick-up/delivery times may vary slightly from what is listed on this page.</p>
 

<h3>How to navigate this page:</h3>
<ul>
<li>Clicking on the name of the library will display information about that library as it appears in the State Library of Iowa’s Iowa Library Directory.</li>
<li>Click each column to sort in ascending or descending order.</li>
<li>Click on the route number to display all of the libraries who share that route and a map showing the route.</li>
<li>Use the search box to search all of the data, such as county, route number, etc.</li>
</ul>
     '.$varColDump
  );  // end render array

  return $page;
}


?>

