#!/bin/bash

# Zabbix bits
# UserParameter=custom.iowa_courier_log_length,cat /tmp/courier_log.log | wc -l
# UserParameter=custom.iowa_courier_log_age,find /tmp/courier_log.log -type f -mtime +1|wc -l



# Make sure all the leftover stuff isn't running
ps -ef | grep firefox | grep -v grep | awk '{print $2}' | xargs sudo kill -9
ps -ef | grep Xvfb | grep -v grep | awk '{print $2}' | xargs sudo kill -9
ps -ef | grep selenium | grep -v grep | awk '{print $2}' | xargs sudo kill -9

rm -f /tmp/.X99-lock

# run the selenium stuff
selenium/start_selenium &

sleep 5

./ia_shares_import.pl --log /home/ma/iowa_courier_data_import/courier_log.log --drupal-config /production/sites/default/settings.php --full

# Make sure all the leftover stuff isn't running
ps -ef | grep firefox | grep -v grep | awk '{print $2}' | xargs sudo kill -9
ps -ef | grep Xvfb | grep -v grep | awk '{print $2}' | xargs sudo kill -9
ps -ef | grep selenium | grep -v grep | awk '{print $2}' | xargs sudo kill -9
