<?php

function datatrac_permission()
{
    return array(
        'access datatrac data' => array(
            'title' => t('Datarack administration'),
            'description' => t('Perform administration tasks for my module.'),
        ),
    );
}

#Creating a menu access
function datatrac_menu()
{
    $items['mcs-display'] = array(
        'title' => 'MOBIUS Courier Statistics (ARCHIVED)',
        'page callback' => 'get_user_page',
        #'page callback' => 'test_select',
        #'page arguments' => array(1),
        #'access callback' => 'example_user_access',
        'access arguments' => array('access datatrac data'),
        'type' => MENU_NORMAL_ITEM,
    );
    return $items;
}

function get_user_page()
{
    drupal_add_js(drupal_get_path("module", "datatrac") . '/jquery-1.12.4.js', 'external');
    drupal_add_js(drupal_get_path("module", "datatrac") . '/jquery-ui.js', 'external');
    // jquery-ui calls for images that we don't need for this basic page, so, for now, not loading
    // drupal_add_css(drupal_get_path('module', 'datatrac') . '/jquery-ui.css', 'external');
    drupal_add_js(drupal_get_path("module", "datatrac") . '/sortscript.js', 'external');
    
    function getRouteResults($sc, $tsc, $fmd2, $tmd2, $trt, $frt)
    {
        // print "<p>$sc, $tsc, $fmd2, $tmd2, $trt, $frt<br /></p>";
        $query = db_select('dtdata','dtc');
        $query
            ->fields('dtc', array('number','pickuploc','deliveryloc','item', 'pickuploc_code','pickupdate', 'deliverydate','elapsedtime','elapsed_not_counted')) 
            ->condition( 
                db_and() 
                ->condition('dtc.pickupdate', $fmd2, '>=')
                ->condition('dtc.deliverydate', $tmd2, '<=')
                ->condition('dtc.deliveryloc', '%' . db_like($tsc) . '%', 'LIKE')
                ->condition('dtc.pickuploc', '%' . db_like($sc) . '%', 'LIKE')
                ->condition('dtc.deliveryloc_code', '%' . db_like($trt) . '%', 'LIKE')
                ->condition('dtc.pickuploc_code', '%' . db_like($frt) . '%', 'LIKE')
                ->isNotNull('dtc.elapsedtime')
                ->isNotNull('dtc.elapsed_not_counted')
                ->condition('dtc.active', "1", '=')
            )
            ->addExpression('elapsed_not_counted + elapsedtime', 'totaldays');
        // print "<p>$query</p>";
        
        return $query->execute();
    }
    
    function getSummaryLibraryResults($sc, $tsc, $fmd2, $tmd2, $trt, $frt, $days = null, $comparison = null)
    {
        // print "<p>$sc, $tsc, $fmd2, $tmd2, $trt, $frt, $days = null, $comparison = null <br /></p>";
        $query=db_select('dtdata','dtc');
        
        $dband = db_and()
                ->condition('dtc.pickupdate', $fmd2, '>=')
                ->condition('dtc.deliverydate', $tmd2, '<=')
                ->condition('dtc.deliveryloc', '%' . db_like($tsc) . '%', 'LIKE')
                ->condition('dtc.pickuploc', '%' . db_like($sc) . '%', 'LIKE')
                ->condition('dtc.deliveryloc_code', '%' . db_like($trt) . '%', 'LIKE')
                ->condition('dtc.pickuploc_code', '%' . db_like($frt) . '%', 'LIKE')
                ->isNotNull('dtc.elapsedtime')
                ->isNotNull('dtc.elapsed_not_counted')
                ->condition('dtc.active', "1", '=');

        if( isset($days) && isset($comparison) )
        {            
            $dband->condition('dtc.elapsedtime', "$days", $comparison);
        }
        
        $query->fields('dtc', array('elapsedtime'))->condition($dband);
        
        // print "<p>$query</p>";
        return $query->countQuery()->execute()->fetchField();
    }
    
    function getLibraryDropdownArray($type)
    {
        $ret = array();
        $query=db_select('dtdata','lbt');
        $query
            ->fields('lbt', array($type.'loc_code',$type.'loc'))
            ->condition('lbt.active', "1", '=')
            ->groupBy ('lbt.'.$type.'loc')
            ->orderBy('lbt.'.$type.'loc');
        $res = $query->execute();
        
        while($row1 = $res->fetchAssoc())
        {
            $ret[$row1[$type.'loc']] = $row1[$type.'loc'];
        }
        $type == 'pickup' ? $conjunction = "From" : $conjunction = "To";
        
        $topOption=array('Select'=>"Select $conjunction All");
        return $topOption+$ret;
    }

    
/* BEGIN CODE EXECUTION PAGE LOAD */
    if( isset($_POST['fromLib']) AND ($_POST['fromLib']!='Select') )
    {
        $sc=$_POST['fromLib'];
    }
    else
    {
        $sc=null;
        $rows=array();
    }
    
    // print_r($_POST);
    
    if( isset($_POST['toLib'])AND ($_POST['toLib']!='Select') )
    {
        $tsc=$_POST['toLib'];  
    }
    else
    {
        $tsc=null;
    }
    
    if( isset($_POST['dateFrom'])AND ($_POST['dateFrom']!=Null) )
    {
        $fmd=$_POST['dateFrom'];  
    }
    else
    {
        $fmd=null;
    }
    
    if( isset($_POST['dateTo'])AND ($_POST['dateTo']!=Null) )
    {
        $tmd=$_POST['dateTo'];  
    }
    else
    {
        $tmd=null;
    }

    if (($tmd!=Null)||($fmd!=Null))
    {
        $tmd1=strtotime($tmd);
        $tmd2=date('Y-m-d',$tmd1);
        $fmd1=strtotime($fmd);
        $fmd2=date('Y-m-d',$fmd1);
    }
    else
    {
        $tmd2=null;
        $fmd2=null;
    }
    
    if( isset($_POST['fromRoute']) AND ($_POST['fromRoute']!='Select') )
    {
        $frt=$_POST['fromRoute'];  
    }
    else
    {
        $frt='';
        $rows=array();
    }
    
    if( isset($_POST['toRoute'])AND ($_POST['toRoute']!='Select') )
    {
        $trt=$_POST['toRoute'];
    }
    else
    {
        $trt='';
    }
 
    $wLib="";
    
    if( isset($sc) || isset($tsc) || isset($frt) || isset($trt) )
    {
        $rows=array();
        // print "Going to get the data<br />";
        $results = getRouteResults($sc, $tsc, $fmd2, $tmd2, $trt, $frt);
    }

    $deliveryLibraryArrayMenu = getLibraryDropdownArray( 'delivery' );
    $pickupLibraryArrayMenu = getLibraryDropdownArray( 'pickup' );
    
    
    $header=array(t('NUM'),t('Pickup Location'), t('Delivery Location'), t('Barcode Code'), t('Delivery Date'), t('Pickup Date'), t('Dates in Transit'), t('Weekend/ Holiday days'), t('Business days'));
    $headerDvr=array(t('Business days'),t('Same Day'), t('Next Day'), t('Two days'), t('Three Days'), t('Four+ days'));
    $headerOvr=array(t('From'),t('To'), t('Total Bags'), t('Avg Days in Transit'), t('Avg Business Days'));
    
    $rowsOvr=array();
    $ddaysrows=array();
    $arrayDays=array();
    $delLoc=array();
    $ddelLoc=array();
    if( $results )
    {
        $totalBags = getSummaryLibraryResults($sc, $tsc, $fmd2, $tmd2, $trt, $frt);
        $daysInTransit=0;
        $businessDaysInTransit=0;
        $sameDay  = getSummaryLibraryResults($sc, $tsc, $fmd2, $tmd2, $trt, $frt, 0, '=');
        $nextDay  = getSummaryLibraryResults($sc, $tsc, $fmd2, $tmd2, $trt, $frt, 1, '=');
        $twoDay   = getSummaryLibraryResults($sc, $tsc, $fmd2, $tmd2, $trt, $frt, 2, '=');
        $threeDay = getSummaryLibraryResults($sc, $tsc, $fmd2, $tmd2, $trt, $frt, 3, '=');
        $fourDay  = getSummaryLibraryResults($sc, $tsc, $fmd2, $tmd2, $trt, $frt, 3, '>');
        
        foreach ($results as $result)
        {
            $rows[]=array(
                $result->number,
                $result->pickuploc,
                $result->deliveryloc,
                $result->item,
                $result->deliverydate,
                $result->pickupdate,
                $result->totaldays,
                $result->elapsed_not_counted,
                $result->elapsedtime
            );
            
            $daysInTransit+=$result->totaldays;
            $businessDaysInTransit+=$result->elapsedtime;
            
            $libValue = $result->deliveryloc;
            if(is_null($tsc))
            {
                $wLib="From ".$sc." To ".$tsc.":";
            }
            else
            {
                $wLib="To ".$tsc." From ".$sc.":";
                $libValue = $result->pickuploc;
            }
            isset($ddelLoc[$libValue]) ? $ddelLoc[$libValue]++ : $ddelLoc[$libValue] = 1;
        }

        if ($totalBags==0)
        {
            $adit=0;
            $abdt=0;
        }
        else
        {
            $adit=round(($daysInTransit/$totalBags),2);
            $abdt=round(($businessDaysInTransit/$totalBags),2); 
        }
        
        if(is_null($sc)){$sc=null;} else{ $sc=$sc; };
        if(is_null($sc)){$sc="All Libraries";};
        if(is_null($tsc)){$tsc="All Libraries";};
        if( $frt!='' ){$sc=$frt;};
        if( $trt!='' ){$tsc=$trt;};
        $rowsOvr[]=array(t($sc),t($tsc), t($totalBags), t($adit), t($abdt));
        $ddaysrows[]=array(t('<strong>Date Range</strong><br />From&nbsp'.$fmd.'<br />To&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp'.$tmd),t($sameDay),t($nextDay),t($twoDay),t($threeDay),t($fourDay));
    }
        
           
    $headerdloc=array(t($wLib), t('Total Bags'));
    $delRow = array();
    while (list($key, $val) = each($ddelLoc))
    {
        $delRow[]=array($key,$val);
    }
      
$about='<div class="container">
  <div style="
font-size: 15pt;
color: #f22477;
padding: 2em;
width: 69%;
line-height: 2em;">
The Courier Statistics Database provides historical data for courier activity that can be searched and exported according to your needs. Data begins on July 1, 2016 and ended on March 31, 2020 at the outset of the pandemic. Statistics for March, April and May of 2017 are not in the database as during that time STAT changed vendors from Datatrac to Xcelerator.</div>
  <button type="button" class="btn btn-info" data-toggle="collapse" data-target="#demo">Click here for more information</button>
<br /><br />
  <div id="demo" class="collapse">
  
  
 <br />  MOBIUS Courier Statistics Database: What You Need to Know<br /><br />
 
The Courier Statistics Database is an archived data set that is no longer updated.  This database provides historical data for courier activity that can be searched and exported according to your needs. Data begins on July 1, 2016 and runs through March 31, 2020. Statistics for March, April and May of 2017 are not in the database as during that time STAT changed vendors from Datatrac to Xcelerator. If you have any questions about this data set, please contact <a href="mailto:courier@mobiusconsortium.org">courier@mobiusconsortium.org</a>. 

<br /><br />How to Search:<br /><br />

Specify your chosen date range in the indicated fields, then choose your start and end points in the dropdowns below. You may search by library, (terminal entries are for a geographic area), and you may set your institution as either the sending or receiving library. Once the desired date range and your choice of origin and endpoint locations are set, clicking Submit will generate the report. 

<br /><br />

Reading and Exporting Reports:

<br /><br />

When your report is generated, you will see pickup and delivery location information, the barcode for each bag put in transit, pickup and delivery dates, and transit time information. The database takes into account weekends and holidays (when the courier isn’t running), so along with the total Days in Transit figure, you will also see a breakdown of the number of business days versus the number of excluded days for the period of time that the courier handled your materials. Excluded days include weekends, holidays, and non-service days for libraries with less than five days a week delivery. To export your data to a CSV file, click on the link above the data table display.


<br /><br />
  </div>
</div>';
    $terminals='<option value="Select">Select Terminal</option><option value="MO-EA">MO EA Terminal</option><option value="MO-NO">MO NO Terminal</option>'
            . '<option value="MO-NW">MO NW Terminal</option><option value="MO-SE">MO SE Terminal</option>'
            . '<option value="MO-SO">MO SO Terminal</option><option value="MO-SW">MO SW Terminal</option>'
            .'<option value="IA-EA">IA EA Terminal</option><option value="IA-NO">IA NO Terminal</option>'
            . '<option value="IA-NW">IA NW Terminal</option><option value="IA-RIV">IA RIV Terminal</option><option value="IA-SE">IA SE Terminal</option>'
            . '<option value="IA-SO">IA SO Terminal</option><option value="IA-SW">IA SW Terminal</option>';
            
    $fsend1= '<form method="post">Begin Date: <input type="textbox" name="dateFrom" id="datepicker" value="'.$fmd.'" />&nbsp;End Date: <input type="textbox" name="dateTo" id="datepicker2" value="'.$tmd.'" /><br /><br />';
    $fsend3='<select name="fromRoute" style="margin-right:22%">'.$terminals.'</select>';
    $fsend4='<select name="toRoute" style="margin-right:15%">'.$terminals.'</select>';
    $fsend2= '<input type="submit" name="submit" value="Submit" /></div>';
    $toreturnOvr=theme('table', array('header'=>$headerOvr, 'rows'=>$rowsOvr));

    $toreturndLoc=theme('table', array('header'=>$headerdloc, 'rows'=>$delRow,'attributes' => array('class' => array('sortable'))));

    $toreturnDvr=theme('table', array('header'=>$headerDvr, 'rows'=>$ddaysrows));
    $toreturn1=theme('table', array('header'=>$header, 'rows'=>$rows,'attributes' => array('class' => array('sortable'),'id' => array('mytable'))));
    
    $toreturn=theme('select', array('element' => array('From Library','#options' => $pickupLibraryArrayMenu, '#attributes'=>array('name'=>t('fromLib')))));
    $toreturn2=theme('select', array('element' => array('#options' => $deliveryLibraryArrayMenu, '#attributes'=>array('name'=>'toLib'))));
    
    $exportButton="<div class='button'>
                <a href='#' id ='export' role='button'>Click To Export The Table Data into a CSV File
                </a>
            </div>";
    if(is_null($fmd)||(is_null($tmd))){
     return $about."<p style='color:red'>Please Select Date Range</p>".$fsend1.$toreturn.$toreturn2."<br /> Or <br />".$fsend3.$fsend4.$fsend2;  
    } else {
    return $about.$fsend1.$toreturn.$toreturn2."<br /> Or <br />".$fsend3.$fsend4.$fsend2.$toreturnOvr.$toreturnDvr.$toreturndLoc.$exportButton.$toreturn1;
    }


}

