<?php

function datatrac_permission() {
  return array(
    'access datatrac data' => array(
      'title' => t('Datarack administration'),
      'description' => t('Perform administration tasks for my module.'),
    ),
  );
}

#Creating a menu access
function datatrac_menu() {
  $items['mcs-display'] = array(
    'title' => 'MOBIUS Courier Statistics',
    'page callback' => 'get_user_page',
    #'page callback' => 'test_select',
    #'page arguments' => array(1),
    #'access callback' => 'example_user_access',
    'access arguments' => array('access datatrac data'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

function get_user_page(){
    drupal_add_js('/sites/all/modules/datatrack/jquery-1.12.4.js', 'external');
    drupal_add_js('/sites/all/modules/datatrack/jquery-ui.js', 'external');
    drupal_add_css(drupal_get_path('module', 'datatrack') . '/jquery-ui.css', 'external');
    drupal_add_js('/sites/all/modules/datatrack/sortscript.js', 'external');
    //drupal_add_js('/sites/all/modules/datatrack/export_tables.js', 'external');

    function checkWeekend($date_1,$date_2){
        /*
        $date1 = new DateTime($date_1);
        $date2 = new DateTime($date_2);        $daterange = new DatePeriod($date2, new DateInterval('P1D'), $date1);

            foreach($daterange as $date3){
                echo date("Y-m-d", $date3);
                //echo $date;
                //echo isWeekend($date3);
            }
         * */
$wkdc=0;          
$date_from = strtotime($date_2); // Convert date to a UNIX timestamp  
  
// Specify the end date. This date can be any English textual format  
  
$date_to = strtotime($date_1); // Convert date to a UNIX timestamp  
  
// Loop from the start date to end date and output all dates inbetween  
for ($i=$date_from; $i<=$date_to; $i+=86400) {  
    //echo date("Y-m-d", $i).'<br />';  
    if((isWeekend(date("Y-m-d", $i)))=="weekend") {
        $wkdc=$wkdc+1;
    }
           
            
}  
return $wkdc; 
    }
    function isWeekend($date4) {
        /*
         * Check if it is a Holiday
         */
        $day="";
        $day = date('Y-m-d',strtotime($date4));
	$holidays = array(
		'2017-01-02',
                '2017-01-16',
                '2017-05-29',
		'2017-07-04',
                '2017-09-04',
                '2017-11-23',
                '2017-11-24',
                '2016-11-24',
                '2016-11-25',
                '2017-12-25',
                '2018-01-01',
                '2016-12-26',
                '2017-09-05',
                '2016-07-04',
                '2016-05-30'
                
	);
	
	//echo (date('M-d',strtotime('2016-11-06')));
    //return (date('N', strtotime($date)) >= 6);
         $weekDay = date('w', strtotime($date4));
    if ((($weekDay == 0 || $weekDay == 6) )||((in_array($day,$holidays))))
    {
        //echo $day." Holiday";
        return "weekend";
    }   else {
        return "weekday";
    }
}
function dateDifference($date_1 , $date_2  )
{
    /*
    $datetime1 = date_create($date_1);
    $datetime2 = date_create($date_2);
    
    $interval = date_diff($datetime1, $datetime2);
    $differenceFormat = '%a';
    echo $interval->format($differenceFormat);
     * */
    
     $date1 = new DateTime($date_1);
$date2 = new DateTime($date_2);

$diff = $date2->diff($date1)->format("%a");
return $diff;
    
}
 if( isset($_POST['fromLib']) AND ($_POST['fromLib']!='Select') ){
    $sc=$_POST['fromLib'];  
 } else {
     $sc=null;
     $rows=array();
 }
 if( isset($_POST['toLib'])AND ($_POST['toLib']!='Select') ){
    $tsc=$_POST['toLib'];  
 } else {
     $tsc=null;
     $rows1=array();
 }
 if( isset($_POST['dateFrom'])AND ($_POST['dateFrom']!=Null) ){
    $fmd=$_POST['dateFrom'];  
 } else {
     $fmd=null;
     
 }
 if( isset($_POST['dateTo'])AND ($_POST['dateTo']!=Null) ){
    $tmd=$_POST['dateTo'];  
 } else {
     $tmd=null;
     
 }
 
 if (($tmd!=Null)||($fmd!=Null))
 {
     $tmd1=strtotime($tmd);
     $tmd2=date('Y-m-d',$tmd1);
     $fmd1=strtotime($fmd);
     $fmd2=date('Y-m-d',$fmd1);
 }
  else {
     $tmd2=null;
     $fmd2=null;
     
 }
  if( isset($_POST['fromRoute']) AND ($_POST['fromRoute']!='Select') ){
    $frt=$_POST['fromRoute'];  
 } else {
     $frt=null;
     $rows=array();
 }
 if( isset($_POST['toRoute'])AND ($_POST['toRoute']!='Select') ){
    $trt=$_POST['toRoute'];  
 } else {
     $trt=null;
     $rows1=array();
 }
 //echo $frt." AND ".$trt;
 $wLib="";
 //$tmd1=strtotime($tmd);
 //$sc="P- MISSOURI WESTERN STATE UNIVERIST";
 //echo "This date from;".$fmd."This date to;".$tmd."-->".$tmd2;
    //$query=db_select('dtdata','dtc');
    if((( isset($sc) && ($sc!=null) ) OR ( isset($tsc) && ($tsc!=null))) ){
        $query=db_select('dtdata3','dtc');
    $query
            ->fields('dtc', array('number','pickuploc','deliveryloc','item', 'pickuproute','pickupdate', 'deliverydate'))
            #->range(0,50)
            //->groupBy ('dtc.pickuploc')
            //->condition('pickuproute',$sc)
            //->condition('dtc.pickuploc', '%' . db_like($sc) . '%', 'LIKE')
            //->condition('dtc.deliveryloc', '%' . db_like($tsc) . '%', 'LIKE')
            //->condition(db_and()->condition('dtc.pickuploc', '%' . db_like($sc) . '%', 'LIKE')->condition('dtc.deliveryloc', '%' . db_like($tsc) . '%', 'LIKE')->condition('dtc.pickupdate', $fmd2, '>=')->condition('dtc.deliverydate', $tmd2, '<='));
            ->condition(db_and()->condition('dtc.pickuploc', '%' . db_like($sc) . '%', 'LIKE')->condition('dtc.deliveryloc', '%' . db_like($tsc) . '%', 'LIKE')->condition('dtc.pickupdate', $fmd2, '>=')->condition('dtc.deliverydate', $tmd2, '<='));
            ////->condition(db_and()->condition('dtc.pickuploc', '%' . db_like($sc) . '%', 'LIKE')->condition('dtc.deliveryloc', '%' . db_like($tsc) . '%', 'LIKE'))
            //->orderBy('dtc.number');
    $results=$query->execute();
    
    $rows=array();
    }
    
    //Add check for Groups if selection fromRoute or toRoute selected will override individual library selection;
    if(( isset($frt) && ($frt!=null) ) OR ( isset($trt) && ($trt!=null)) ){
       
      unset($results);
      unset($rows);  
            $query=db_select('dtdata3','dtc');
            //$substring_alias = $query->addExpression(substr('dtc.pickuproute',0,2));
    $query
            ->fields('dtc', array('number','pickuploc','deliveryloc','item', 'pickuproute','pickupdate', 'deliverydate'))
            
            #->range(0,50)
            //->groupBy ('dtc.pickuploc')
            //->condition('pickuproute',$sc)
            //->addExpression(substr('dtc.pickuproute',0,2))
            //->condition(db_and()->condition('dtc.pickuproute',  db_like($frt) . '%', 'LIKE'))
            //->condition(db_and()->condition('ktc.pickuproute',  '%', '=')->condition('ktc.pickuproute', 'IA-RIV', '<>'));
            ->condition(db_and()->condition('dtc.deliveryroute',  db_like($trt) . '%', 'LIKE')->condition('dtc.pickuproute',  db_like($frt) . '%', 'LIKE')->condition('dtc.pickupdate', $fmd2, '>=')->condition('dtc.deliverydate', $tmd2, '<=')->condition('dtc.deliveryloc', '%' . db_like($tsc) . '%', 'LIKE')->condition('dtc.pickuploc', '%' . db_like($sc) . '%', 'LIKE'));
            //->condition(db_and()->condition('ktc.pickuproute', db_like($sc) . '%', 'LIKE')->condition('ktc.pickuproute', 'IA-RIV', '<>'));
            //->condition('dtc.deliveryloc', '%' . db_like($tsc) . '%', 'LIKE')
            //->condition(db_and()->condition('dtc.pickuploc', '%' . db_like($sc) . '%', 'LIKE')->condition('dtc.deliveryloc', '%' . db_like($tsc) . '%', 'LIKE')->condition('dtc.pickupdate', $fmd2, '>=')->condition('dtc.deliverydate', $tmd2, '<=')->condition('dtc.pickuproute', 'IA-RIV', '<>'));
            //->condition(db_and()->condition('dtc.pickuploc', '%' . db_like($sc) . '%', 'LIKE')->condition('dtc.deliveryloc', '%' . db_like($tsc) . '%', 'LIKE'))
            //->groupBy ('dtc.deliveryloc');
//->orderBy('dtc.number');
            
            
    $results=$query->execute();
   
    $rows=array();
    }
    //else{
        //$query=db_select('LibCodes','lbc');
    $query2=db_select('dtdata3','lbt');
        $query2
            #->fields('dtc', array('number','pickuploc','deliveryloc','item', 'pickuproute'))
         //->fields('lbc', array('LibCode','LocName'))
         ->fields('lbt', array('number','pickuploc','pickuproute','deliveryloc'))
            #->range(0,50)
           //->groupBy ('lbc.LibCode')
          //  ->condition('lbt.pickuproute', 'IA-RIV', '<>') condition to exclude Iowa Libraries
            ->groupBy ('lbt.deliveryloc')
            ->orderBy('lbt.deliveryloc');
    //}
    $results2=$query2->execute();
    $query=db_select('dtdata3','lbc');
        $query
            #->fields('dtc', array('number','pickuploc','deliveryloc','item', 'pickuproute'))
         //->fields('lbc', array('LibCode','LocName'))
         ->fields('lbc', array('number','pickuploc','pickuproute','deliveryloc'))
            #->range(0,50)
           //->groupBy ('lbc.LibCode')
           // ->condition('lbc.pickuproute', 'IA-RIV', '<>') condition to exclude Iowa Librarties
            ->groupBy ('lbc.pickuploc')
            ->orderBy('lbc.pickuploc');
    //}
    $results1=$query->execute();
    $header=array(t('NUM'),t('Pickup Location'), t('Delivery Location'), t('Barcode Code'), t('Delivery Date'), t('Pickup Date'), t('Dates in Transit'), t('Weekend/ Holiday days'), t('Business days'));
    $headerDvr=array(t('Business days'),t('Same Day'), t('Next Day'), t('Three Days'), t('Four days'), t('More than Four days'));
    $headerOvr=array(t('From'),t('To'), t('Total Bags'), t('Avg Days in Transit'), t('Avg Business Days'));
    $secondmenu=array();
    $rows1=array();
    $rowsOvr=array();
    $ddaysrows=array();
    $cnt=0;$tdit=0;$tabdt=0;
    $arrayDays=array();
    $delLoc=array();$dLoc=array();
    $ddelLoc=array();$new = array();
    if((( isset($sc) && ($sc!=null) ) OR ( isset($tsc) && ($tsc!=null)) ) OR (( isset($frt) && ($frt!=null) ) OR ( isset($trt) && ($trt!=null)) )){
    foreach ($results as $result) {
        $cnt=$cnt+1;
        //$dif=date_diff($result->pickupdate, $result->deliverydate);
        $dit=dateDifference($result->deliverydate,$result->pickupdate);
        $chkwnd=checkWeekend($result->deliverydate,$result->pickupdate);
        
        $rows[]=array(
            $result ->number,
            substr($result->pickuploc,2),
            //strtoupper($result->deliveryloc),
            $result->deliveryloc,
            $result->item,
            $result->deliverydate,
            $result->pickupdate,
            //date_format((strtotime($result->deliverydate)-strtotime($result->pickupdate)),'%a')
            //dateDifference($result->deliverydate,$result->pickupdate)
            $dit+1,
            $chkwnd,
            ($dit+1)-$chkwnd
        );
       $tdit=$tdit+($dit+1);
       $tabdt=$tabdt+($dit+1-$chkwnd);
       array_push($arrayDays,(($dit+1)-$chkwnd));
       if(is_null($tsc)){
           $wLib="From ".substr($sc,2)." To ".$tsc.":";
       //array_push($delLoc,strtoupper($result->deliveryloc));
       array_push($delLoc,$result->deliveryloc);
       } else {
           $wLib="To ".$tsc." From ".$sc.":";
         array_push($delLoc,substr($result->pickuploc,2));  
       }
    
    }
       foreach ($delLoc as $delLib){
    $ddelLoc[$delLib]=count_array_values($delLoc,$delLib);
    }
    if ($cnt==0){
        $adit=0;
        $abdt=0;
    } else {
    $adit=round(($tdit/$cnt),2);
    $abdt=round(($tabdt/$cnt),2); 
    }
    if(is_null($sc)){$sc=null;} else{ $sc=substr($sc, 2);};
    if(is_null($sc)){$sc="All Libraries";};
    if(is_null($tsc)){$tsc="All Libraries";};
    if($frt){$sc=$frt;};
    if($trt){$tsc=$trt;};
    $rowsOvr[]=array(t($sc),t($tsc), t($cnt), t($adit), t($abdt));
    //$rows[]=array(t(''),t('Total bags:'),$cnt,t('From ').$sc, t('To ').$tsc,t('Avarage Days in Transit'),$adit,t(''),$abdt);
    //print_r($arrayDays);
    //echo "\n"."One day ".count_array_values($arrayDays, 1). " time(s)."."\n"; 
    //echo "\n"."Two days ".count_array_values($arrayDays, 2). " time(s)."."\n"; 
    //echo "\n"."Three day ".count_array_values ($arrayDays, 3). " time(s)."."\n"; 
    //echo "\n"."More than three days ".count_array_values_larger($arrayDays, 3). " time(s)."."\n";
    $ddaysrows[]=array(t('<strong>Date Range</strong><br />From&nbsp'.$fmd.'<br />To&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp'.$tmd),t(count_array_values($arrayDays, 1)),t(count_array_values($arrayDays, 2)),t(count_array_values($arrayDays, 3)),t(count_array_values($arrayDays, 4)),t(count_array_values_larger($arrayDays, 4)));
    //array_push($ddaysrows,t(''),count_array_values($arrayDays, 1),count_array_values($arrayDays, 2),count_array_values($arrayDays, 3),count_array_values_larger($arrayDays, 3));
    //echo "\n"."Five day ".count_array_values($arrayDays, 5). " time(s)."."\n"; 
    
                


    } //else {
    ?>

        <?php
        
           while($row1 = $results1->fetchAssoc())
            {
               $senco='';
               //$secondmenu[]=array((strtolower($row['LibCode']))=>$row['LocName']);
               //$secondmenu2[]=array((strtolower($row['LibCode']))=>$row['LocName']);
               $senco=str_replace("- ","-",$row1['pickuploc']);
                  //$senco=substr($row1['pickuploc'],2); 
               
		$secondmenua[$row1['pickuploc']] = substr($senco,2);
                
                //$secondmenu2a[$row1['deliveryloc']] = strtoupper($row1['deliveryloc']);
                
                /*
                $secondmenu[$row1['LocName']] = $row1['LocName'];
                $secondmenu2[$row1['LocName']] = $row1['LocName'];
                 */
                //$secondmenu2[$row1['LibCode']] = $row1['LocName'];//original search by route code
                //$secondmenu.="<option value = ".(strtolower($row['deliveryroute']))." >".($row['deliveryloc'])." </option>";
            }  
            while($row2 = $results2->fetchAssoc())
            {
               //$secondmenu[]=array((strtolower($row['LibCode']))=>$row['LocName']);
               //$secondmenu2[]=array((strtolower($row['LibCode']))=>$row['LocName']);
               
		//$secondmenua[$row1['pickuploc']] = substr($row1['pickuploc'],2);
                
                //$secondmenu2a[$row2['deliveryloc']] = strtoupper($row2['deliveryloc']);
                $secondmenu2a[$row2['deliveryloc']] = $row2['deliveryloc'];
                /*
                $secondmenu[$row1['LocName']] = $row1['LocName'];
                $secondmenu2[$row1['LocName']] = $row1['LocName'];
                 */
                //$secondmenu2[$row1['LibCode']] = $row1['LocName'];//original search by route code
                //$secondmenu.="<option value = ".(strtolower($row['deliveryroute']))." >".($row['deliveryloc'])." </option>";
            } 
            //foreach ($row2 as $onelib){
        //$deliveryCount=array($onelib[2],t(count_array_values($rows,$onelib[2])));
        
    //}
$headerdloc=array(t($wLib), t('Total Bags'));
$delRow=array();
while (list($key, $val) = each($ddelLoc)) {
    $delRow[]=array($key,$val);
}
   //print_r($dLoc);
          $secondmenup=array('Select'=>'Select From All');
          $secondmenu=$secondmenup+$secondmenua;
          $secondmenu2p=array('Select'=>'Select To All');
          $secondmenu2=$secondmenu2p+$secondmenu2a;
        ?>   

<?php
    //}
$about='<div class="container">
  
  <button type="button" class="btn btn-info" data-toggle="collapse" data-target="#demo">About STAT module</button>
<br /><br />
  <div id="demo" class="collapse">
   <br /> MOBIUS Courier Statistics Database: What You Need to Know<br /><br />

The Courier Statistics Database provides historical data for courier activity that can be searched and exported according to your needs. Data begins on July 1, 2016, and is updated after the first of every month. <u>Statistics for the current month are <b>not</b> included in the database.</u><!--Data begins on June 1, 2017, and is current for the last whole month.  Statistics since then are not included in the database, updates will be posted after 1 st day of the current month.--> Statistics for March, April and May of 2017 are not in the database. During that time the courier stat was transferred to Xlerator. If you are looking for a bag that is currently outstanding or a transaction that is less than a month old, please contact <a href="mailto:courier@mobiusconsortium.org">courier@mobiusconsorium.org</a>
<br /><br />
How to Search:<br /> <br />
Specify your chosen date range in the indicated fields, then choose your start and end points in the dropdowns below. You may search by library or by route (terminal), and you may set your institution as either the sending or receiving library. Once the desired date range and your choice of origin and endpoint locations are set, clicking Submit will generate the report. 
<br /><br />
Reading and Exporting Reports:<br /><br />
When your report is generated, you will see pickup and delivery location information, the barcode for each bag put in transit, pickup and delivery dates, and transit time information. The database takes into account weekends and holidays (when the courier isn’t running), so along with the total Days in Transit figure, you will also see a breakdown of the number of business days versus the number of weekend/holiday days for the period of time that the courier handled your materials. To export your data to a CSV file, click on the link above the data table display. 
<br /><br />
  </div>
</div>';
    $terminals='<option value="Select">Select Terminal</option><option value="MO-EA">MO EA Terminal</option><option value="MO-NO">MO NO Terminal</option>'
            . '<option value="MO-NW">MO NW Terminal</option><option value="MO-SE">MO SE Terminal</option>'
            . '<option value="MO-SO">MO SO Terminal</option><option value="MO-SW">MO SW Terminal</option>'
            .'<option value="IA-EA">IA EA Terminal</option><option value="IA-NO">IA NO Terminal</option>'
            . '<option value="IA-NW">IA NW Terminal</option><option value="IA-RIV">IA RIV Terminal</option><option value="IA-SE">IA SE Terminal</option>'
            . '<option value="IA-SO">IA SO Terminal</option><option value="IA-SW">IA SW Terminal</option>'
            /*
    .'<option value="RTE 1">RTE 1 Terminal</option><option value="RTE 2">RTE 2 Terminal</option><option value="RTE 3">RTE 3 Terminal</option><option value="RTE 4">RTE 4 Terminal</option>'
            .'<option value="RTE 5">RTE 5 Terminal</option><option value="RTE 6">RTE 6 Terminal</option><option value="RTE 7">RTE 7 Terminal</option><option value="RTE 8">RTE 8 Terminal</option>'
            .'<option value="RTE 9">RTE 9 Terminal</option><option value="RTE 10">RTE 10 Terminal</option><option value="RTE 11">RTE 11 Terminal</option><option value="RTE 12">RTE 12 Terminal</option>'
            */;
    $fsend1= '<form method="post">Begin Date: <input type="textbox" name="dateFrom" id="datepicker" />&nbsp;End Date: <input type="textbox" name="dateTo" id="datepicker2" /><br /><br />';
    $fsend3='<select name="fromRoute" style="margin-right:22%">'.$terminals.'</select>';
    $fsend4='<select name="toRoute" style="margin-right:15%">'.$terminals.'</select>';
    $fsend2= '<input type="submit" name="submit" value="Submit" /></div>';
    $toreturnOvr=theme('table', array('header'=>$headerOvr, 'rows'=>$rowsOvr));
    if(( isset($frt) && ($frt!=null) ) OR ( isset($trt) && ($trt!=null)) ){
            $toreturndLoc="";
        } else {
            $toreturndLoc=theme('table', array('header'=>$headerdloc, 'rows'=>$delRow,'attributes' => array('class' => array('sortable'))));
    }
    $toreturnDvr=theme('table', array('header'=>$headerDvr, 'rows'=>$ddaysrows));
    $toreturn1=theme('table', array('header'=>$header, 'rows'=>$rows,'attributes' => array('class' => array('sortable'),'id' => array('mytable'))));
    //$toreturn=theme_select('element' => array('#options' => $secondmenu));
    //$toreturn=theme('select', array('element' => array('#options' => array($secondmenu1, $secondmenu2))));
    $toreturn=theme('select', array('element' => array('From Library','#options' => $secondmenu, '#attributes'=>array('name'=>t('fromLib')))));
    $toreturn2=theme('select', array('element' => array('#options' => $secondmenu2, '#attributes'=>array('name'=>'toLib'))));
    $exportButton="<div class='button'>
                <a href='#' id ='export' role='button'>Click To Export The Table Data into a CSV File
                </a>
            </div>";
    if(is_null($fmd)||(is_null($tmd))){
     return $about."<p style='color:red'>Please Select Date Range</p>".$fsend1.$toreturn.$toreturn2."<br /> Or <br />".$fsend3.$fsend4.$fsend2;  
    } else {
    return $about.$fsend1.$toreturn.$toreturn2."<br /> Or <br />".$fsend3.$fsend4.$fsend2.$toreturnOvr.$toreturnDvr.$toreturndLoc.$exportButton.$toreturn1;
    }

}
/*
 * Count the number of times the delivey in days occur
 */
function count_array_values($my_array, $match) 
{ 
    $count = 0; 
    
    foreach ($my_array as $key => $value) 
    { 
        if ($value == $match) 
        { 
            $count++; 
        } 
    } 
    
    return $count; 
} 
function count_array_values_larger($my_array, $match) 
{ 
    $count = 0; 
    
    foreach ($my_array as $key => $value) 
    { 
        if ($value > $match) 
        { 
            $count++; 
        } 
    } 
    
    return $count; 
}



