<?php

/**
 * Generates and returns a string of digits representing the time of the
 * current system in microseconds granularity. 
 * 
 * Compared to the standard time() function, the microtime() function is more 
 * accurate and in addition, successive quick calls inside a loop generate 
 * unique results; which can be quite useful in certain cases. 
 * 
 * Our function below generates digits only output based on the time stamp
 * generated by the microtime() function.
 * 
 * @return string
 */
function get_clean_microtimestamp_string() {
    //Get raw microtime (with spaces and dots and digits)
    $mt = microtime();

    //Remove all non-digit (or non-integer) characters
    $microts = "";
    $mtparts = explode(' ', $mt);
    $mt = $mtparts[1].$mtparts[0];
    $length = strlen($mt);
    for($i = 0; $i < $length; $i++) {
        if(ctype_digit($mt[$i])) {
            $microts .= $mt[$i];
        }
    }

    //Return
    return $microts;
}
function array_has_duplicates($array) {
   return count($array) !== count(array_unique($array));
}

$microtimes = array();
for($i = 0; $i < 10000; $i++) {
    $microtimes[] = get_clean_microtimestamp_string();
    usleep(1);
}

foreach($microtimes as $microtime) {
    echo $microtime . "\n";
}

if(array_has_duplicates($microtimes)) {
    echo "FOUND DUPLICATES!\n";
}
else {
    echo "NO DUPLICATES FOUND. AWESOME!\n";
}
?>
