<?php
/**
* Implements hook_menu().
*/
function bnl_menu()
{
  $items['borrowing_n_lending'] = array(
    'title' => 'Borrowing and Lending',
    'page callback' => 'mobius_bnl_display',
    'access arguments' => array('access content'),
  );
  $items['borrowing_n_lending_get'] = array(
    'title' => 'Borrowing and Lending',
    'page callback' => 'mobius_bnl_postback',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function mobius_bnl_display()
{
  drupal_page_is_cacheable($allow_caching = FALSE);
  drupal_add_css('/sites/all/libraries/chosen/chosen.css', 'external');
  drupal_add_js('/sites/all/libraries/chosen/chosen.jquery.js', 'external');
  drupal_add_js('/sites/all/libraries/chosen/monthpicker/MonthPicker.min.js', 'external');
  drupal_add_js('https://cdn.jsdelivr.net/momentjs/latest/moment.min.js', 'external');
  drupal_add_js('https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js', 'external');
  drupal_add_css('https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css', 'external');
  drupal_add_css('/sites/all/libraries/chosen/monthpicker/MonthPicker.min.css', 'external');

  $page = array (
    '#markup' =>
    '
    <div class="messages status">If this is your first time here, please <a id="firsttimebutton" href="#instructions" >read the instructions</a>.</div>
    <span id="mobius_bnl_page_is_loaded"></span>
    <div id="bnl_panel">
    <div id="bnl_filter_select_master_container">
        
        <div class="bnl_basic_filter_container">
        <div class="bnl_title_container">Library Selection</div>
            <div class="bnl_dropdown_wrapper">
                <div id="bnl_basic_filter_branch_owning" class="bnl_dropdown">
                </div>
                LIBRARY
            </div>
        </div> <!-- bnl_basic_filter_container -->

        <div class="bnl_filter_switcher_container">
            <a id="filter_switcher_button">Show <span id="filter_switcher_word">Advanced</span> filters</a>
        </div> <!-- bnl_basic_filter_container -->

        <div class="bnl_advanced_filter_container hide">
        <div class="bnl_title_container">Lending Library</div>
            <div class="bnl_dropdown_wrapper">
                <div id="bnl_filter_branch_owning" class="bnl_dropdown">
                </div>
                LIBRARY
            </div>
            <div class="bnl_dropdown_wrapper">
                <div id="bnl_filter_cluster_owning" class="bnl_dropdown">
                </div>
                CLUSTER/STANDALONE
            </div>
            <div class="bnl_dropdown_wrapper">
                <div id="bnl_filter_system_owning" class="bnl_dropdown">
                </div>
                SYSTEM
            </div>
        </div> <!-- bnl_advanced_filter_container -->

        <div class="bnl_advanced_filter_container hide">
        <div class="bnl_title_container">Borrowing Library</div>
            <div class="bnl_dropdown_wrapper">
                <div id="bnl_filter_branch_borrowing" class="bnl_dropdown">
                </div>
                LIBRARY
            </div>
            <div class="bnl_dropdown_wrapper">
                <div id="bnl_filter_cluster_borrowing" class="bnl_dropdown">
                </div>
                CLUSTER/STANDALONE
            </div>
            <div class="bnl_dropdown_wrapper">
                <div id="bnl_filter_system_borrowing" class="bnl_dropdown">
                </div>
                SYSTEM
            </div>
        </div> <!-- bnl_advanced_filter_container -->

        <div class="bnl_advanced_filter_container hide">
            <input type="checkbox" name="show-zeros" id="show_zeros"></input><label id="show_zeros_label" for="show_zeros">Show Zeros</label>
        </div> <!-- bnl_advanced_filter_container -->

        <div id="bnl_date_div">
            <div id="date_range_title">Date Range</div>
            <div class="date_dropdown_wrapper">
                <label for="date_from">From</label>
                <input class="chosen_date_display" id="date_from"></input>
                <input class="date_dropdown" id="date_from_d" pop="#date_from" widget="#date_from_widget" type="text" />
                <div class="date_widget" id="date_from_widget"></div>
            </div>
            <div class="date_dropdown_wrapper">
                <label for="date_to">To</label>
                <input class="chosen_date_display" id="date_to"></input>
                <input class="date_dropdown" id="date_to_d" pop="#date_to" widget="#date_to_widget" type="text" />
                <div class="date_widget" id="date_to_widget"></div>
            </div>
        </div> <!-- bnl_date_div -->
    
    <div id="bnl_submit_container"><div id="bnl_submit_button">Get Results!</div></div>
    
    </div> <!-- bnl_filter_select_master_container -->
    <div id="bnl_data_tables">

        <div id="bnl_my_lending_div"></div>

        <div id="bnl_my_borrowing_div"></div>

        <div id="bnl_lib_to_lib_div"></div>

    </div>
    <div id="bnl_pie"></div>
    
    </div> <!-- bnl_panel -->
    
    <hr />
    <div id="instructions_show_hide"><a href="#instructions" id="instructions_show_hide_a" >Show/hide instructions</a></div>
  <div class="bnl_instructions" style="display: none">
  <h2><a name="instructions"></a>Instructions</h2>
  <h3>Purpose</h3>
    <p>
    This tool is used to explore the Borrowing and Lending statistics for the MOBIUS consortium participating libraries.
    You can use this tool to explore the data at a glance and/or produce spreadsheet reports.
    </p>
    <h3>Basics</h3>
  <ol>
    <li><a href="#choosingdate">Choose a date</a></li>
    <li><a href="#choosinglibrary">Choose an Owning Library (optional)</a></li>
    <li><a href="#choosinglibrary">Choose a Borrowing Library (optional)</a></li>
    <li>Choose "Show Zeros" if you want the results to include the instances where no materials were shared</li>
    <li>Click "Get Results!"</li>
    <li><a href="#exploreresults">Explore the results</a></li>
    <li><a href="#downloadresults">Download the results</a></li>
  </ol>
  
  <h3><a name="choosingdate"></a>
    Choosing a date</h3>
  <p>Dates are expressed in terms of "whole months"</p>
  <ol>
    <li>Click inside the box located below the phrase "Date Range"
      <br>
    <img src="../../misc/bnl/bnl_calendar.png" alt="Date Range widget highlighting the options on the left">
    </li>
    
    <li>This will cause a calendar widget to appear. There are some quick links for "Last Month", "Two Months Ago", "Three Months Ago", "Four Months Ago" and "Custom Range". 
      <ol>
        <li>If you need to specify <b>more than one month</b>
          <ul>
            <li>Cilck on "Custom Range"</li>
            <li>Cilck on the arrow buttons on the top-left/top-right until you have arrived at your starting month</li>
            <li>Cilck on ANY day within the month</li>
            <li>Cilck on the arrow button on the top-right until you have arrived at your destination month</li>
            <li>Cilck on ANY day within the destination month</li>
          </ul>
        </li>
        <li>If you need to specify a <b>single month more than four months ago</b>
          <ul>
            <li>Cilck on "Custom Range"</li>
            <li>Cilck on the arrow buttons on the top-left/top-right until you have arrived at your starting month</li>
            <li>Cilck on ANY day in the first half of the month</li>
            <li>Cilck on a day in the month greater than the starting day</li>
          </ul>
        </li>
      </ol>
    </li>
    </ol>
  
  <h3><a name="choosinglibrary"></a>
    Choosing a library</h3>
  <p>This tool allows you to choose more than one library.</p>
  <p>You do not need to make a selection from any of the dropdown menus. Choosing nothing means "all" options are included.</p>
  <p>When you click into any of the selection boxes, you will see the choices dropdown below your cursor:</p>
  <img src="../../misc/bnl/bnl_library_dropdown_list.png" alt="Dropdown list showing listing of libraries with search box">
  <p>You may choose an option by clicking it. <b>You may search for an option by typing partial words in the box above the list.</b> After you make a selection:</p>
  <img src="../../misc/bnl/bnl_library_dropdown_list_one_selected.png" alt="Dropdown list with one selected and option is now greyed out">
  <p>You may click into the dropdown box again and make additional selections. You are only allowed to choose the same option once.</p>
  <div class="messages status">NOTE: After you choose an option from one dropdown, you will not be allowed to choose an option from another dropdown in the same group</div>
  <p>Choosing options from the "Cluster" or "System" dropdowns will include any libraries that are connected to that selection. You may choose more than one.</p>
  <div class="messages status">Hint: If you would like to know the details for your library for both Borrowing and Lending, you may need to run this reporting tool twice; once with your library chosen from the Owning category and once with your library chosen from the Borrowing category.</div>
  <h3><a name="exploreresults"></a>
    Explore the results</h3>
  <p>After the data has been populated from the server, you should see four tables.</p>
  <ol>
  <li>
  Owning Summary
  <br /><img src="../../misc/bnl/bnl_owning_summary.png" alt="Owning summary header image"><br />
  <ul>
  <li>This table shows total items <b>lent</b> by the included librar(ies). It provides a sum for each filtered library and each month within the selected range (if data exists).</li>
  </ul>
  </li>
  <li>
  Borrowing Summary
  <br /><img src="../../misc/bnl/bnl_borrowing_summary.png" alt="Borrowing summary header image"><br />
  <ul>
  <li>This table shows total items <b>borrowed</b> by the included librar(ies). It provides a sum for each filtered library and each month within the selected range (if data exists).</li>
  </ul>
  </li>
  <li>
  Library to Library
  <br /><img src="../../misc/bnl/bnl_lib_to_lib.png" alt="Library to library header image"><br />
  <p>This table shows the details. It shows the total of items lent for each possible combination of libraries within the selected criteria.
  <div class="messages status">NOTE: This will show a sum total for ALL months included in the specified month range.</div>
  </p>
  </li>
  <li>
  Cluster to Cluster
  <br /><img src="../../misc/bnl/bnl_cluster_to_cluster.png" alt="Cluster to cluster header image"><br />
  <p>This table is similar to the "Library to Library" table. Instead of displaying the individual library, this table shows the cluster to which the specified librar(ies) belong. It shows the total items lent for each possible combination of libraries within the selected criteria.
  <div class="messages status">NOTE: This table DOES NOT include any libraries that were not specified. The totals are only for the libraries chosen. Instead of displaying the library names, it shows the associated cluster(s).</div>
  </p>
  </li>
  </ol>
  <p>
  <b>A word about using the tools provided by each table</b>
  <br />
  <p>Each table can be <b>searched</b>
  <br /><img src="../../misc/bnl/bnl_table_search_box.png" alt="Result table search box highlighted"><br />
  As you type into the searchbox, the table will immediately begin to filter the results to match your criteria. All columns are searched.
  </p>
  <p>Each table can display more <b>results per page</b>
  <br /><img src="../../misc/bnl/bnl_table_per_page.png" alt="Result table results per page shown"><br />
  Click the dropdown menu and choose the desired number of results you would like the table to display at once.
  </p>
  <p>Each table has <b>pagination</b>
  <br /><img src="../../misc/bnl/bnl_table_pagination.png" alt="Result table showing pagination"><br />
  If the results do not fit onto your specified number of results per page, you will need to page through. Click on the page number and/or the "Next" and "Previous" buttons.
  </p>
  <p>Each table can be <b>sorted by column(s)</b>
  <br /><img src="../../misc/bnl/bnl_table_sort.png" alt="Result table showing clickable column headers and sort arrow indication"><br />
  Click on a column header in order to sort by that column. The faint arrows next to each column header indicate the direction of the sort (shown here in red).
  <br />
  You can sort by <b>multiple</b> columns. Do this by first sorting by one column, then hold the &lt;SHIFT&gt; key and click another column.
  </p>
  
  <h3><a name="downloadresults"></a>
    Download the results</h3>
  <p>You may download the results of any of the tables. Each table contains a clickable link labeled "Download Spreadsheet".
  When clicked, you will be prompted to download a CSV file. This file may be opened with Microsoft Excel or Libre Calc or any other spreadsheet application.
  <div class="messages status">NOTE: The spreadsheet will contain <b>ALL</b> of the results of the table regardless of any search you may have performed on it</div>
  </p>
  
  </div>
     '
  );  // end render array

  return $page;
}

function mobius_bnl_postback()
{
    $data_array = array();
    if(isset($_GET['startdate']) && isset($_GET['enddate']))
    {
        mobius_borrowing_n_lending_json();  // calling headers
        $clusters = array
        (
            'owning' => ($_GET['cluster_owning'] ? $_GET['cluster_owning'] : ''),
            'borrowing' => ($_GET['cluster_borrowing'] ? $_GET['cluster_borrowing'] : '')
        );
        $clusters['owning'] .= ($_GET['system_owning'] ? ','.$_GET['system_owning'] : '');
        $clusters['borrowing'] .= ($_GET['system_borrowing'] ? ','.$_GET['system_borrowing'] : '');
        $clusters['owning'] = preg_replace('/^,?(.*)/','$1', $clusters['owning']);
        $clusters['borrowing'] = preg_replace('/^,?(.*)/','$1', $clusters['borrowing']);
        $branchArray = array
        (
            'bnl_owning_name.id' => $_GET['branch_owning'],
            'bnl_borrowing_name.id' => $_GET['branch_borrowing'],
            'owning_cluster_ids.cid' => $clusters['owning'],
            'borrowing_cluster_ids.cid' => $clusters['borrowing']
        );

        mobius_bnl_get_bnl_base($data_array, $_GET['startdate'], $_GET['enddate'], $branchArray);

        echo $data_array = drupal_json_encode($data_array);
    }
    else if(isset($_GET['get_branches']))
    {
        mobius_borrowing_n_lending_json();  // calling headers
        mobius_bnl_get_all_branches($data_array);
        echo $data_array = drupal_json_encode($data_array);
    }
    else if(isset($_GET['get_data_date_range']))
    {
        mobius_borrowing_n_lending_json();  // calling headers
        mobius_bnl_get_data_date_ranges($data_array);
        echo $data_array = drupal_json_encode($data_array);
    }

}

function mobius_bnl_get_data_date_ranges(&$data_array)
{
    $data_array["date_start"] = "";
    $data_array["date_end"] = "";
     $query = "
        SELECT 'min' as \"type\",DATE_FORMAT(MIN(borrow_date), '%m/%Y') as \"date\" from mobius_bnl_bnl
        UNION ALL
        SELECT 'max' as \"type\",DATE_FORMAT(MAX(borrow_date), '%m/%Y') as \"date\" from mobius_bnl_bnl
        ";
    $result = db_query($query);
    while($libraryRow = $result->fetchAssoc())
    {
        if($libraryRow["type"] =="min")
        {
            $data_array["date_start"] = $libraryRow["date"];
        }
        else
        {
            $data_array["date_end"] = $libraryRow["date"];
        }
    }
}

function mobius_bnl_get_all_branches(&$data_array)
{
    $data_array["branch"] = array();
    $data_array["cluster"] = array();
    $data_array["branch_to_cluster"] = array();
    $data_array["branch_order"] = array();
    $used = array();
    // First get the overall branch names and clusters to which they belong
     $query = "
       SELECT
        fid,fname,cid,cname,ctype
        FROM
        mobius_bnl_branch_connection_map
        order by lower(fname)
        ";
    $result = db_query($query);
    while($libraryRow = $result->fetchAssoc())
    {
        // Record the order
        if(!$used[$libraryRow["fid"]])
        {
            $used[$libraryRow["fid"]] = 1; 
            $data_array["branch_order"][] = $libraryRow["fid"];
        }
        // Record the branches
        if(!$data_array["branch"][$libraryRow["fid"]])
        {
            $data_array["branch"][$libraryRow["fid"]] = $libraryRow["fname"];
        }
        // Record the Clusters
        if(!$data_array["cluster"][$libraryRow["cid"]])
        {
           $data_array["cluster"][$libraryRow["cid"]] = array('name' => $libraryRow["cname"], 'type' => $libraryRow["ctype"]);
        }

        // Connect branches to clusters
        if(!$data_array["branch_to_cluster"][$libraryRow["fid"]])
        {
            $data_array["branch_to_cluster"][$libraryRow["fid"]] = array();
        }
        $data_array["branch_to_cluster"][$libraryRow["fid"]][$libraryRow["cid"]] = 1;
    }
}

function mobius_bnl_get_bnl_base(&$data_array, $startDate, $endDate, $branchSelections)
{
    
    $data_array["amount_branch"] = array();
    $data_array["amount_cluster"] = array();

    $gotmore = 1;
    $offset = 0;
    $chunk = 1000;
    $totalRows = 0;
    while($gotmore > 0)
    {
        $columns = "";
        $vals = array($startDate, $endDate);
        
        $columns = "
           SELECT
           'lent' as \"type\",
           bnl.borrow_date \"borrow_date\",
           bnl_borrowing_name.name \"borrowing_branch_name\", bnl_borrowing_name.id \"borrowing_branch_id\",
           bnl_owning_name.name \"owning_branch_name\", bnl_owning_name.id \"owning_branch_id\",
           (select min(cid) from mobius_bnl_branch_connection_map where fid=bnl_borrowing_branch.final_branch) \"borrowing_cluster_id\",
           (select min(cid) from mobius_bnl_branch_connection_map where fid=bnl_owning_branch.final_branch) \"owning_cluster_id\",
           sum(bnl.quantity) \"quantity\"";
    
        $fromClauseStart = "
            FROM 
            mobius_bnl_bnl bnl,
            mobius_bnl_branch bnl_borrowing_branch,
            mobius_bnl_branch bnl_owning_branch,
            mobius_bnl_branch_name_final bnl_borrowing_name,
            mobius_bnl_branch_name_final bnl_owning_name
            WHERE
            bnl_borrowing_name.id = bnl_borrowing_branch.final_branch and
            bnl_owning_name.id = bnl_owning_branch.final_branch and
            bnl.borrowing_branch = bnl_borrowing_branch.id and
            bnl.owning_branch = bnl_owning_branch.id and
            bnl.borrow_date between str_to_date( concat(?,'-01') ,'%Y-%m-%d') and str_to_date( concat(?,'-01') ,'%Y-%m-%d')
            and bnl.quantity > 0
            ";

        $fromClause = mobius_bnl_get_bnl_base_branches_from_clause($fromClauseStart, $vals, $branchSelections, 0);
        $groupClause = " group by 1,2,3,4,5,6,7,8";
        
        $query = $columns.$fromClause.$groupClause;

        $query .= "
        UNION ALL

        SELECT
           'borrow' as \"type\",
           bnl.borrow_date \"borrow_date\",
           bnl_borrowing_name.name \"borrowing_branch_name\", bnl_borrowing_name.id \"borrowing_branch_id\",
           bnl_owning_name.name \"owning_branch_name\", bnl_owning_name.id \"owning_branch_id\",
           (select min(cid) from mobius_bnl_branch_connection_map where fid=bnl_borrowing_branch.final_branch) \"borrowing_cluster_id\",
           (select min(cid) from mobius_bnl_branch_connection_map where fid=bnl_owning_branch.final_branch) \"owning_cluster_id\",
           sum(bnl.quantity) \"quantity\"";
       $vals[] = $startDate;
       $vals[] = $endDate;
       $fromClause = mobius_bnl_get_bnl_base_branches_from_clause($fromClauseStart, $vals, $branchSelections, 1);
       $query .= $fromClause.$groupClause;
        
        $query .= "
            limit $chunk
            offset $offset";
// echo preg_replace('/\n/','<br>',$query);
// print_r($vals);
// exit;
        
        $result = db_query($query,$vals);
        while($libraryRow = $result->fetchAssoc())
        {
            if(!$data_array[$libraryRow["type"]])
            {
                $data_array[$libraryRow["type"]] = array();
            }
            if(!$data_array[$libraryRow["type"]][$libraryRow["borrow_date"]])
            {
                $data_array[$libraryRow["type"]][$libraryRow["borrow_date"]] = array();
            }
            if(!$data_array[$libraryRow["type"]][$libraryRow["borrow_date"]][$libraryRow["borrowing_branch_id"]])
            {
                $data_array[$libraryRow["type"]][$libraryRow["borrow_date"]][$libraryRow["borrowing_branch_id"]] = array();
            }
            if(!$data_array[$libraryRow["type"]][$libraryRow["borrow_date"]][$libraryRow["borrowing_branch_id"]][$libraryRow["owning_branch_id"]])
            {
                $data_array[$libraryRow["type"]][$libraryRow["borrow_date"]][$libraryRow["borrowing_branch_id"]][$libraryRow["owning_branch_id"]] = ($libraryRow["quantity"] + 0);
            }
            else
            {
                $data_array[$libraryRow["type"]][$libraryRow["borrow_date"]][$libraryRow["borrowing_branch_id"]][$libraryRow["owning_branch_id"]] += ($libraryRow["quantity"] + 0);
            }

            // Add up totals for each whole cluster
            if(!$data_array["amount_cluster"][$libraryRow["borrowing_cluster_id"]])
            {
                $data_array["amount_cluster"][$libraryRow["borrowing_cluster_id"]] = array();
            }
            if(!$data_array["amount_cluster"][$libraryRow["borrowing_cluster_id"]][$libraryRow["owning_cluster_id"]])
            {
                $data_array["amount_cluster"][$libraryRow["borrowing_cluster_id"]][$libraryRow["owning_cluster_id"]] = ($libraryRow["quantity"] + 0);
            }
            else
            {
                $data_array["amount_cluster"][$libraryRow["borrowing_cluster_id"]][$libraryRow["owning_cluster_id"]] += ($libraryRow["quantity"] + 0);
            }
        }
        
        $gotmore = $result->rowCount();
        $totalRows+=$gotmore;
        unset($rows);
        unset($result);
        $offset += $chunk;
    }
    $data_array["query"] = $query;
    $data_array["result_rows"] = $totalRows;
}

function mobius_bnl_get_bnl_base_branches_from_clause($fromClause, &$vals, $branchSelections, $reverse)
{
    if($reverse)
    {
        // echo "reversing <br>";
        $temp = $branchSelections['bnl_owning_name.id'];
        $branchSelections['bnl_owning_name.id'] = $branchSelections['bnl_borrowing_name.id'];
        $branchSelections['bnl_borrowing_name.id'] = $temp;

        $temp = $branchSelections['owning_cluster_ids.cid'];
        $branchSelections['owning_cluster_ids.cid'] = $branchSelections['borrowing_cluster_ids.cid'];
        $branchSelections['borrowing_cluster_ids.cid'] = $temp;
        // print_r($branchSelections);
    }
    foreach ($branchSelections as $key => $value)
    {
        if(strlen($value) > 0)
        {
            $clause = "\nAND (";
            $something = 0;
            $values = explode(',',$value);
            $collection = "";
            foreach($values as $id)
            {
                if(is_numeric($id)) // only digits allowed here
                {
                    $something = 1;
                    if(preg_match("/cluster/", $key)) // Clusters are handled differently
                    {
                        $collection.="$id,";
                    }
                    else
                    {
                        $clause .= "\n$key = ? \nOR";
                        $vals[] = $id;
                    }
                }
            }
            if(preg_match("/cluster/", $key)) // Clusters are handled differently
            {
                $collection = substr($collection,0,-1); // chop off the last ,
                $type = ( preg_match("/owning/", $key) ? "owning" : "borrowing");
                $type = "bnl_".$type."_name.id";
                $clause .= "$type IN (SELECT fid FROM mobius_bnl_branch_connection_map WHERE cid IN ( $collection ) ) \n)";
            }
            else
            {
                $clause = substr($clause,0,-2); // chop off the last "OR"
                $clause .= ")\n";
            }
            $fromClause = ($something ? $fromClause.$clause : $fromClause);

        }
    }
    return $fromClause;
}

function mobius_borrowing_n_lending_json() {
  drupal_add_http_header('Content-Type', 'application/json');
  //drupal_add_http_header('Access-Control-Allow-Origin', "*");
  //drupal_add_http_header('Access-Control-Allow-Methods', 'GET,PUT,POST,DELETE');
 }
 
?>

